CREATE USER 'ecommerceapp'@'localhost' IDENTIFIED BY 'ecommerceapp';

GRANT ALL PRIVILEGES ON * . * TO 'ecommerceapp'@'localhost';

#
# Starting with MySQL 8.0.4, the MySQL team changed the 
# default authentication plugin for MySQL server 
# from mysql_native_password to caching_sha2_password.
#
# The command below will make the appropriate updates for your user account.
#
# See the MySQL Reference Manual for details: 
# https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html
#
ALTER USER 'ecommerceapp'@'localhost' IDENTIFIED WITH mysql_native_password BY 'ecommerceapp';

-- -----------------------------------------------------
-- Schema full-stack-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `full-stack-ecommerce`;

CREATE SCHEMA `full-stack-ecommerce`;
USE `full-stack-ecommerce` ;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(2000) DEFAULT NULL,
  `name` VARCHAR(2000) DEFAULT NULL,
  `description` VARCHAR(2000) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(2000) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO PRODUCT_CATEGORY(CATEGORY_NAME) VALUES ('Technology');
INSERT INTO PRODUCT_CATEGORY(CATEGORY_NAME) VALUES ('Science fiction');
INSERT INTO PRODUCT_CATEGORY(CATEGORY_NAME) VALUES ('Novel');
INSERT INTO PRODUCT_CATEGORY(CATEGORY_NAME) VALUES ('Thriller');

-- -----------------------------------------------------
-- Technology
-- -----------------------------------------------------
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1000', 'Crash Course in Python', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://rukminim2.flixcart.com/image/850/1000/kwnv6a80/book/f/s/r/python-crash-course-original-imag9amydwwp5apy.jpeg?q=90', 1, 100, 14.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1001', 'Become a Guru in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/41+WuzI18rL.jpg', 1, 100, 20.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1002', 'Exploring Vue.js', 'Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://ultimatecourses.com/assets/blog/vue/exploring-vuejs-an-introduction-to-vuejs-2152a2d0d378a596da474c7c69eade9c6d8fc368f4f9e3f99fd4f166e1393334.png', 1, 100, 14.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1003', 'Advanced Techniques in Big Data', 'Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://media.springernature.com/full/springer-static/cover-hires/book/978-981-16-3607-3', 1, 100, 13.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1004', 'Crash Course in Big Data', 'Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://www.selecthub.com/wp-content/uploads/2017/12/Crash-Course-in-Big-Data.png', 1, 100, 18.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1005', 'JavaScript Cookbook', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/81aiC00tNGS._AC_UF350,350_QL50_.jpg', 1, 100, 23.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1006', 'Beginners Guide to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/611KPh473wL._AC_UF1000,1000_QL80_.jpg', 1, 100, 14.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1007', 'Advanced Techniques in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/31GDmPpuuDL.jpg', 1, 100, 16.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1008', 'Introduction to Spring Boot', 'Learn Spring Boot at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/41jlVHUifoS.jpg', 1, 100, 25.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1009', 'Become a Guru in React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/41jlVHUifoS.jpg', 1, 100, 23.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1010', 'Beginners Guide to Data Science', 'Learn Data Science at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://rukminim2.flixcart.com/image/850/1000/xif0q/book/5/o/h/a-beginners-guide-to-data-science-original-imaghhxwr5vbk8yu.jpeg?q=20', 1, 100, 24.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1011', 'Advanced Techniques in Java', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/71Ntq3AKT5L._AC_UF1000,1000_QL80_.jpg', 1, 100, 19.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1012', 'Exploring DevOps', 'Learn DevOps at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHFdJv1mXRvtVL-FSTYpRaKjEwQ97U21ljeQ&usqp=CAU', 1, 100, 24.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1013', 'The Expert Guide to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/41DmBcI7bqL._AC_UF1000,1000_QL80_.jpg', 1, 100, 19.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1014', 'Introduction to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGh-vTgiHONDp6XZJx2ZqvKxubgj_KmXL34g&usqp=CAU', 1, 100, 22.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1015', 'The Expert Guide to JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/71xWbDCCFDL._AC_UF1000,1000_QL80_.jpg', 1, 100, 22.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1016', 'Exploring React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/41IiBTZOGCL.jpg', 1, 100, 27.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1017', 'Advanced Techniques in React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/41yqXfybJzL.jpg', 1, 100, 13.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1018', 'Introduction to C#', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/616FRviKnNL._AC_UF1000,1000_QL80_.jpg', 1, 100, 26.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1019', 'Crash Course in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/71aLMmLBCuL._AC_UF1000,1000_QL80_.jpg', 1, 100, 13.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1020', 'Introduction to Machine Learning', 'Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/61j4G-2yFiL._AC_UF1000,1000_QL80_.jpg', 1, 100, 19.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1021', 'Become a Guru in Java', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/61spHPaD7XL.jpg', 1, 100, 18.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1022', 'Introduction to Python', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/91ELJ94KTRL._AC_UF1000,1000_QL80_.jpg', 1, 100, 26.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1023', 'Advanced Techniques in C#', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/61h0IzCuR-L._AC_UF1000,1000_QL80_.jpg', 1, 100, 22.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Technology-Genre-1024', 'The Expert Guide to Machine Learning', 'Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'https://m.media-amazon.com/images/I/51D6-QdcAsL.jpg', 1, 100, 16.99, 1, NOW());

-- -----------------------------------------------------
-- Science fiction
-- -----------------------------------------------------
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1001', 'The Cherokee Rose', 'Three women uncover the secrets of a Georgia plantation that embodies the intertwined histories of Indigenous and enslaved Black communities—the fascinating debut novel, inspired by a true story, of the National Book Award-winning and New York Times bestselling author of All That She Carried , now featuring a new introduction.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1680075765l/62926991.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1002', ' Night Sweeper', 'Cray is a Night Sweeper. Twenty-five years old, amazingly lethal, and brilliant beyond anyones right to be, night after endless night, he has one job: kill Festers, zombie-like freaks born of the United States Presidents foolish choice to use chemical warfare against his foes.', 'https://m.media-amazon.com/images/I/811X486B4sL._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1003', 'The Time Machine', 'H.G. Wells, the author, has been called the father of science fiction.The Time Machine is one of his most notable science fictions. Its a Time Travellers journey into the future. He explains that there are really four limensions, three of which we call the three planes of the Space, and a fourth, Time.', 'https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/81HifkpAdNL._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1004', 'The Picture of Dorian Gray', 'Artist Basil Hallward has sent a gift. A portrait that perfectly captures young Dorian Grays handsome features. When Lord Henry tempts Dorian with a new lifestyle of hedonism and pleasure, he realizes that he would sell his soul for an eternity of debauchery. Oscar Wildes only published novel, The Picture of Dorian Gray is a dark and sinful story of excess and vice.', 'https://m.media-amazon.com/images/I/91luhSxt+5L._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1005', 'Columbia Pictures Horror, Science Fiction and Fantasy Films', 'Covers more than 200 Columbia feature films within these genres, among them Close Encounters of the Third Kind, Seventh Voyage of Sinbad, Earth vs. The Flying Saucers and The Revenge of Frankenstein. Also discussed are films starring horror icons Boris Karloff, Bela Lugosi, and John Carradine.', 'https://m.media-amazon.com/images/I/61+ObhkadqL._AC_UF894,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1006', 'Worthing Chronicle ', 'In suspended animation for fifteen thousand years, Jason Worthing, a telepath, awakes to see what has happened to the colony he had established ', 'https://m.media-amazon.com/images/I/91+KvAdEscS._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1007', 'Oak Cliff: A Tale of Darkness and Despair', 'Oak Cliff Farm has been plagued by tragedy, nightmares, and horror for over one hundred and fifty years. The house itself presents its dark history through flashbacks, hidden clues, and ghostly occurrences to Merline Madagascar, who is a house-whisperer of sorts. ', 'https://m.media-amazon.com/images/I/81mtMSKyvoL._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1008', 'Tachyon: Die Waffe | Harte Science Fiction', 'Brandon Q. Morris is a physicist and space specialist. He has long been concerned with space issues, both professionally and privately and while he wanted to become an astronaut, he had to stay on Earth for a variety of reasons. ', 'https://m.media-amazon.com/images/I/91vsf-mWuaL._AC_UF894,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1009', 'Childhoods End ', 'An all-time Science Fiction classic with a new Millennial Introduction and revised 1990 first chapter as an appendix. Silent spacecraft take the light from the world. superintelligent aliens rule with wisdom not force. A new era of invention and prosperity brings hope and peace. The twilight of the human race has begun.', 'https://m.media-amazon.com/images/I/71wIKzvKsOL._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1010', 'INHIBITOR PHASE', 'A stellar new science fiction adventure from the author who redefined space opera, set in his bestselling Revelation Space universe. For thirty years a tiny band of humans has been sheltering in the caverns of an airless, crater-pocked world called Michaelmas. Beyond their solar system lie the ruins of human interstellar civilization, stalked by a ruthless, infinitely patient cybernetic entity determined to root out the last few bands of survivors. ', 'https://m.media-amazon.com/images/I/81YTSW0oSwL._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1011', 'Fall to Earth', 'Indiana Beckhams lifelong goal has just been cut down. Banned from competing in Olympic fencing, she jumps at the chance to join a research project that could make her the best. But to unlock the promise of her unlimited potential, Indiana must endure a risky, life-altering transformation…', 'https://m.media-amazon.com/images/I/41m0T7VZwAL.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1012', 'The Scenturion Spy: Book Two', 'IN THIS SECOND book of The Scenturion Spy series, Dr. Milt Davidson has been recruited from the Empire State University (ESU) in New York, where he is an academic pathologist, to spy for the CIA. Since the Russians are developing bioweaponry based on odors that activate receptors in the nose and affect the brain', 'https://m.media-amazon.com/images/I/51YC6HTWPWL._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1013', 'Science Friction: Where the Known Meets the Unknown', 'A scientist pretends to be a psychic for a day―and fools everyone. An athlete discovers that good-luck rituals and getting into "the zone" may, or may not, improve his performance. A son explores the possiblities of alternative and experimental medicine for his cancer-ravaged mother. And a skeptic realizes that it is time to turn the skeptical lens onto science itself.', 'https://m.media-amazon.com/images/I/71wkRR7G27L._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1014', 'Classic Science Fiction (Word Cloud Classics)', 'Lovecraft, Edgar Allen Poe, Jack London, Fitz James O Brien, Charlotte Perkins Gilman, and Stanley G. Weinbaum. The exploration of new concepts and technologies has driven the genre since its earliest days, and these works demonstrate how science fiction evolved to encompass not only speculative science but also humanitys role in the universe.', 'https://m.media-amazon.com/images/I/910G6P37JtL._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1015', 'Azura Ghost: 2 (The Graven, 2) ', 'One man and his sentient starship is all that stands between the multiverse and its total destruction in the second book of Essa Hansens brilliant, mind-bending space opera trilogy perfect for fans of The Expanse and A Long Way to a Small Angry Planet.', 'https://m.media-amazon.com/images/I/815t1+-1ToL._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1016', 'Quantum Leap: The Complete Series', 'Get ready for an adventure of many lifetimes with the ground-breaking sci-fi classic, QUANTUM LEAP. Enjoy all 97 thrilling episodes from 5 seasons of the Emmy® Award-winning series as you leap through back-to-back and uninterrupted on Blu-ray for the first time ever! Join Dr. Sam Beckett (Scott Bakula), a time traveler lost in time, who temporarily leaps into the bodies and lives of other people to "put right what once went wrong." Accompanied by Al (Dean Stockwell), a wise-cracking holograph that only Sam can see and hear, Sam twists the hands of fate with each heart-pounding, action-packed adventure in the hopes that he can someday complete the mission that will take him home.', 'https://m.media-amazon.com/images/I/91QBbCeBf4L._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1017', 'Light Years and Dark: Science fiction and fantasy of and for our time', 'Its a collection of stories, so of course the tone varies. Michael Bishop is an extremely talented writer and proves here that hes a more than competent editor as well. Its a pretty fat book, so Id think most readers would find something to like in it.', 'https://m.media-amazon.com/images/I/41MnHvEHnfL._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Science-fiction-1018', 'How to Draw and Paint Science Fiction Art: A Complete Course in Building Your Own Futurescapes and Characters, from Scientific Marvels to Dark, Dystopian Visions', 'The Illustrated History of Science Fiction Comics” is a perfect guidebook to learning about science fiction comic books. It includes pictures and information from comics dating back to the 20s up to the 90s. The book also lists publishers, as well as comic books based on TV and movies.', 'https://m.media-amazon.com/images/I/71PQ-B3iZnL._AC_UF1000,1000_QL80_.jpg', 1, 100, 18.99, 2, NOW());


-- -----------------------------------------------------
-- Novel
-- -----------------------------------------------------
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1000', 'Murder On The Orient Express', 'An American tycoon lies dead in his compartment, stabbed a dozen times, his door locked from the inside. Isolated and with a killer in their midst, detective Hercule Poirot must identify the murderer – in case he or she decides to strike again.', 'https://5.imimg.com/data5/ANDROID/Default/2021/1/NA/UL/TT/118981820/product-jpeg-500x500.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1001', 'THE PRIVATE LIFE OF AN INDIAN PRINCE BY MULK RAJ ANAND', 'The Private Life of an Indian Prince is a novel by Mulk Raj Anand first published in 1953. This book deals with the abolition of the princely states system in India.', 'https://www.bookgeeks.in/wp-content/uploads/2018/01/The-Private-Life-of-an-Indian-Prince-Mulk-Raj-Anand.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1002', 'UNTOUCHABLE BY MULK RAJ ANAND', 'Untouchable was inspired by Anands aunts experience when she had a meal with a Muslim woman and was treated as an outcast by his family.The plot of this book revolves around the argument for eradicating the caste system.', 'https://www.bookgeeks.in/wp-content/uploads/2018/01/Untouchable-Mulk-Raj-Anand.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1003', 'THE ROOM ON THE ROOF BY RUSKIN BOND', 'The Room on the Roof is the story of an orphaned Anglo-Indian boy, Rusty, living in a European colony in Dehradun with his guardian Mr. Harrison, who wants him to stay away from Indians and groom him as a pure Englishman.', 'https://www.bookgeeks.in/wp-content/uploads/2018/01/The-Room-on-the-Roof-Ruskin-Bond.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1004', 'THE WHITE TIGER BY ARAVIND ADIGA', 'The White Tiger provides a darkly humorous perspective of India’s class struggle in a globalized world. The novel has been well-received, making the New York Times bestseller list in addition to winning the Man Booker Prize.', 'https://www.bookgeeks.in/wp-content/uploads/2018/01/The-White-Tiger-by-Aravind-Adiga.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1005', 'A SUITABLE BOY BY VIKRAM SETH', 'A Suitable Boy by Vikram Seth is set in a newly post-independence, post-partition India.The novel follows the story of four families over a period of 18 months, and centres on Mrs Rupa Mehra’s efforts to arrange the marriage of her younger daughter, Lata, to a “suitable boy”.It is one of the longest novels published in a single volume in the English language.', 'https://www.bookgeeks.in/wp-content/uploads/2018/01/A-Suitable-Boy-by-Vikram-Seth.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1006', 'SEA OF POPPIES BY AMITAV GHOSH', 'At the heart of the story of Sea of Poppies is a vast ship, the Ibis.Her destiny is a tumultuous voyage across the Indian Ocean shortly before the outbreak of the Opium Wars in China and onboard are a diverse cast of characters.Another famous novel by Amitav Ghosh is “The Hungry Tide”.', 'https://www.bookgeeks.in/wp-content/uploads/2018/01/Sea-of-Poppies-by-Amitav-Ghosh.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1007', 'NARCOPOLIS BY JEET THAYIL', 'Narcopolis by Jeet Thayil is about the lives of a few people, bound together by a common passion – Opium, and about Bombay, in a way we have never heard of before.Bombay is stripped of its glamour, riches, beaches, and skylines and we are taken to Shuklaji Street, to Rashid’s opium den, and are impelled to see the other side of Bombay.', 'https://www.bookgeeks.in/wp-content/uploads/2017/03/Narcopolis-by-Jeet-Thayil-e1490551566743.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1008', 'FASTING, FEASTING BY ANITA DESAI', 'Fasting, Feasting by Anita Desai is the story of a family living in a small town in India, where provincial customs and attitudes dictate the future of all children: girls are to be married off and boys are to become as educated as possible.', 'https://www.bookgeeks.in/wp-content/uploads/2018/01/Fasting-Feasting-by-Anita-Desai.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1009', 'Pan  (English, Paperback, Robichaud Paul)', 'Part-goat, part-man, Pan bridges the divide between the human and animal worlds. In exquisite prose, Paul Robichaud explores how Pan has been imagined in mythology, art, literature, music, spirituality and popular culture through the centuries. At times, Pan is a dangerous, destabilizing force; at others, a source of fertility and renewal. His portrayals reveal shifting anxieties about our own animal impulses and our relationship to nature. Always the outsider, he has been the god of choice for gay writers, occult practitioners, and New Age mystics. Though ancient sources announced his death, he has lived on through the work of Arthur Machen, Gustav Mahler, Kenneth Grahame, D. H. Lawrence and countless others. Pan: The Great Gods Modern Return traces his intoxicating dance.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNX6_RtXAre7Dd0HbTwc85BZqICeeKbH7Aha2Ns49d2GYbUAu9zejIpEHEkDzbBRRIBMQ&usqp=CAU', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1010', 'Phase', 'E. C. Newman is a storyteller at heart. Born and raised wherever the military sent her family, she never found a direction for her writing until she found herself in Ancient History her freshman year of college, desperate to stay awake. Bringing stories alive in FanFiction, poetry, and original work gave E. C. the distraction she needed and the confidence to add a Writing Major to her bachelors degree. After a stint in acting school in Los Angeles, she gained a MA in Writing for Young People from Bath Spa University in Bath, England.E.C. currently lives in Georgia with her dog of indeterminate breed, where she teaches high school English and assistant directs in the theatre. She cant help but find it hilarious that she’s now teaching how to write an essay when she so hated them as a student herself. In her spare time, E. C. reads too much, watches too much, and laughs just enough. She actively avoids growing up by writing stories about high school and the trials and triumphs that accompany it.', 'https://m.media-amazon.com/images/I/71E2D8NGKnL._AC_UF894,1000_QL80_.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1011', 'Falling: A Novel', '#1 NATIONAL BESTSELLER * INSTANT NEW YORK TIMES BESTSELLER “T. J. Newman has written the perfect thriller! A must-read.” —Gillian Flynn “Stunning and relentless. This is Jaws at 35,000 feet.” —Don Winslow “Falling is the best kind of thriller…Nonstop, totally authentic suspense.” —James Patterson “Amazing...Intense suspense, shocks, and scares...Chilling.” —Lee ChildYou just boarded a flight to New York. There are one hundred and forty-three other passengers onboard. What you dont know is that thirty minutes before the flight your pilots family was kidnapped. For his family to live, everyone on your plane must die. The only way the family will survive is if the pilot follows his orders and crashes the plane. Enjoy the flight.', 'https://m.media-amazon.com/images/I/71Iw79oBg+S._AC_UF1000,1000_QL80_.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1012', 'Wispy Kindle Edition', 'Have you ever looked into the sky and watched as a playful scene unfolded with the clouds? Welcome to the world of Wispy, one of the little clouds that make us smile when we take the time to look up. Wispy seeks different ways that he and his friends can find—their favorite things to do—that brighten the days for those of us with our feet on the ground.', 'https://m.media-amazon.com/images/I/41KQxstDZyL.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1013', 'Arlington Park: A Novel ', 'Arlington Park, a modern-day English suburb very much like its American counterparts, is a place devoted to the profitable ordinariness of life. Amidst its leafy avenues and comfortable houses, its residents live out the dubious accomplishments of civilization: material prosperity, personal freedom, and moral indifference. In Arlington Park, men work, women look after children, and people generally do whats expected of them. Its a world awash in contentment but empty of belief, and riven with strange anxieties', 'https://m.media-amazon.com/images/I/71tWuI6e4EL._AC_UF1000,1000_QL80_.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1014', 'Novel Gazing: Queer Readings in Fiction (Series Q)', 'Offers a collection of queer criticism on the history of the novel. This title includes startingly imaginative essays that explore critical practices that can weave the pleasures and disorientations of reading into the fabric of queer analyses.', 'https://m.media-amazon.com/images/I/41dNpwcjxBL._AC_UF894,1000_QL80_.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1015', 'Azura: Royal Blood', 'The royal occupants of Paris Pigalle Palace are back for the third installment of the Pigalle Palace Series.Pigalle Palace hasnt been the same since Princess Azuras death. King Ulysses has one demand and that is to revive his aunt no matter the cost. There is only one way she can come back; she has to drink the blood of the Prototype, Evan Oleander, but hes dead or so they thought.', 'https://m.media-amazon.com/images/I/71P95Xz2ekL._AC_UF1000,1000_QL80_.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1016', 'Carny Knowledge ("Quantum Leap") ', 'One of a series of novels based on the television series "Quantum Leap", about the adventures of a time-travelling physicist and his helpful hologram.', 'https://m.media-amazon.com/images/I/51MB4e1KS8L._AC_UF1000,1000_QL80_.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1017', 'Light Years: the thrilling new novel from the author of The 100 series: Light Years Book One Kindle Edition', 'Hotshot pilot Vesper, an ambitious Tridian citizen, dreams of becoming a captain - but when she loses her spot to a brilliant, wisecracking boy from the wrong side of the asteroid belt, it makes her question everything she thought she knew. Growing up on the toxic planet Deva, Cormak will take any chance he can get to escape his dead-end life and join the Academy - even if he has to steal someones identity to do it. Arran was always considered an outsider on icy Chetire, always dreaming of something more than a life working in the mines. Now an incoming cadet, Arran is looking for a place to belong - he just never thought that place would be in the arms of a Tridian boy.', 'https://m.media-amazon.com/images/I/51PjIQgMIiL.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Novel-1018', 'Ladies Tailor', 'This is a story of Gurdev and his cohort, a group of refugees who travel east from Pakistan after Partition. It is a tale of falling apart and coming together as the world burns around them.Will Gurdev be successful in his new business of making garments for women? Will he find love after his wife and children leave his side? There may be uncertainty here, but there is also relentless hope.Journey back in time and experience the refugee spirit as Ladies Tailor captures you with all its romance, adventure and one mans iron will to not just survive, but to thrive with new beginnings.', 'https://m.media-amazon.com/images/I/91mD-Cra4eL._AC_UF1000,1000_QL80_.jpg', 1, 100, 17.99, 3, NOW());


-- -----------------------------------------------------
-- Thriller
-- -----------------------------------------------------
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1000', 'The Silent Patient, by Alex Michaelides', 'The standout 2019 thriller follows Alicia Berenson, a celebrated painter married to a famed fashion photographer. But one day, she shoots her husband in the face...five times...and never speaks again.', 'https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/51vqByJ-vML._AC_SR300,300.jpg', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1001', 'Stillhouse Lake, by Rachel Caine', 'An average housewifes life is changed forever when a car accident reveals that her husband is a serial killer. She quickly goes into hiding and assumes a new identity—but soon, as you can probably guess, a new threat finds her', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1555349382-41RTt7alEqL.jpg?crop=0.998xw:1xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1002', 'Behind Closed Doors, by B.A. Paris', 'Picture-perfect newlyweds Jack and Grace are the couple you love to hate. He has the money and perfect job, and she is a beautiful homemaker. But when you look closer, theyre almost too flawless, and Grace is nearly unreachable and impossible to get to know—eerily so.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1555349762-51q2B-R-inrL.jpg?crop=0.998xw:1xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1003', 'In a Dark, Dark Wood, by Ruth Ware', 'Reclusive writer Leonora attends whats supposed to be an exciting, care-free bachelorette weekend in the English countryside, but it soon turns into something sinister in this psychological thriller.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1555351539-619p8s6M37L.jpg?crop=1.00xw:0.968xh;0,0.0200xh&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1004', 'it Ends with Her, by Brianna Labuskes', 'FBI agent Clarke Sinclair has spent years trying to catch a serial killer named Simon Cross. He has a habit of targeting only redheads, but when he breaks his pattern, Clarke must figure out what hes up to.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1576774487-51KEqq2ImrL.jpg?crop=1xw:0.999xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1005', 'An Anonymous Girl, by Greer Hendricks and Sarah Pekkanen', ' This hypnotic novel packs an unexpected twist as it follows a woman named Jessica Farris, who enters into a psychological study to earn extra money. The experiments are led by Dr. Shields, who soon takes the study beyond the lab, infiltrating Jessicas real life.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1692821936-71tsmfzdF1L.jpg?crop=1xw:1xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1006', 'The Wife Between Us, by Greer Hendricks and Sarah Pekkanen', 'All assumptions go out the window with this twisted story of a suffering ex-wife whos stalking her exs new, younger fiancée. But a twist you wont see coming is what makes this story truly stand out.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1555349450-41ckuoGw6hL.jpg?crop=1.00xw:0.986xh;0,0.0100xh&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1007', 'My Lovely Wife, by Samantha Downing', 'In this thriller thats been described as Dexter meets Mr. and Mrs. Smith, a seemingly everyday couple has gotten bored with their monotonous life...so they spice it up. With murder.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1692822704-91oCy8rsEqL.jpg?crop=1xw:1xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1008', 'Before I Go to Sleep, by S.J. Watson', 'In this unnerving thriller, a woman with amnesia fights to discover who she is, despite her inability to recover her past or form new memories.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1555366567-51fYg6NRV2L.jpg?crop=1xw:0.993xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1009', 'The Maidens, by Alex Michaelides', 'The author of The Silent Patient delivers another book that relishes in both unexpected twists and references to classic mythology. In The Maidens, Mariana Andros is summoned back to her alma mater, Cambridge, after her nieces best friend is murdered. Originally there for emotional support, Mariana begins to build a case against the charismatic professor who seems to be at the center of the crime.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1619021908-41WehnULo7L._SL500_.jpg?crop=1xw:0.990xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1010', 'Lock Every Door, by Riley Sager', 'Jules Larson becomes an apartment sitter at Manhattans elite and mysterious building the Bartholomew. She soon befriends another apartment sitter named Ingrid—but when she disappears, Jules must investigate and delve into the buildings dark history.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1692822648-91UKAASiqDL.jpg?crop=1xw:1xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1011', 'The Perfect Nanny by Leïla Slimani', 'Remember The Nanny Diaries? Well, this is like if someone brushed the pages of that book with arsenic. Inspired by a real-life event that took place on the Upper West Side in 2012, Leïla Slimanis first book to be published in the United States starts with the unthinkable: A nanny murders the two children in her charge, then attempts to kill herself. The story then jumps back in time several months, inviting readers to try and figure out how—and why—this terrible thing happened.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1593649522-9780143132172_p0_v5_s1200x630.jpg?crop=1xw:1xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1012', 'The Turn of the Key, by Ruth Ware', 'Rowan Caine seems to score herself a dream job as a live-in nanny at a luxurious smart home in the Scottish Highlands. But what seems too good to be true actually is, as Rowan eventually finds herself in prison and on trial for a murder she insists she didnt commit.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1692822547-61n-x0tsdvL.jpg?crop=1xw:1xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1013', 'The Disappearing Act, by Catherine Steadman', 'Author Catherine Steadman is an actress you may recognize from Downton Abbey. She uses her years in the biz to inform this glossy thriller set in Hollywood during pilot-casting season, when actors vie for parts in new shows. Mia Eliot is an English actress who, in her pursuit of a big break, ends up getting swept into big trouble when another actress disappears.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1692822440-81ZXLf5HTLL.jpg?crop=1xw:1xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1014', 'The Upstairs House, by Julia Fine', 'The Upstairs House is an intellectual, thought-provoking thriller. When her husband leaves for a business trip, Megan is left alone with her new daughter. But shes not exactly alone. It appears that Margaret Wise Brown, author of Goodnight Moon and subject of Megans thesis, is living in the apartment upstairs. Never mind the fact that Brown is long dead—Megan sees her, and shes willing to watch Megans daughter. Then, Margarets ex-lover, a woman poet named Michael Strange, appears, and Megan finds herself in a ghostly tale of regret and revenge.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1627926671-41wCdBf0DFL._SL500_.jpg?crop=1xw:0.993xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1015', 'Long Bright River, by Liz Moore', 'An O, The Oprah Magazine review of Long Bright River called Liz Moores novel equal parts literary and thrilling—a compassionate, multidimensional look at an epidemic that surrounds us. A spin on the procedural, the novel follows a police officer who is consumed by looking for her missing sister, last seen struggling with a heroin addiction.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1591981074-51J6mgYAiyL.jpg?crop=0.989xw:1xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1016', 'The Girl on the Train, by Paula Hawkins', 'Created into a 2016 drama starring Emily Blunt, this story follows Rachel Watson, a commuter who catches sight of the same alluring couple every day while on her train ride. But on one ride, she witnesses something shocking, and she unexpectedly becomes embroiled in an ever-complicated investigation.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1555351651-51Dn7fYoHbL.jpg?crop=1.00xw:0.962xh;0,0.0280xh&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1017', 'These Violent Delights, by Micah Nemerever', 'These Violent Delights will appeal to readers who like their thrillers laced with desire and echoes of Patricia Highsmith. In Micah Nemerevers debut, two lonely college boys find the companionship theyve craved from everyone else. In that cocoon, they devise a strange game—one that involves getting away with the perfect crime, just to see if they can. But can they, really?', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1627926746-417TDU36xZL._SL500_.jpg?crop=0.980xw:1xh;center,top&resize=980:*', 1, 100, 16.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('Thriller-1018', 'My Sister, the Serial Killer, by Oyinkan Braithwaite', 'This award-winning novel follows a woman named Korede as she loyally cleans up after and covers for her sociopathic sister, Ayoola—who appears to have now killed her third boyfriend.', 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1576774132-51gcFBRHprL.jpg?crop=1.00xw:0.984xh;0,0.00600xh&resize=980:*', 1, 100, 16.99, 4, NOW());
